name: braid_ui
description: An experimental UI framework and successor to owo-ui
version: 0.1.0
repository: https://github.com/gliscowo/braid_ui

publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  diamond_gl:
    hosted: https://pub.wispforest.io
    version: ^4.0.0
  ffi: ^2.1.4
  logging: ^1.2.0
  vector_math: ^2.1.4
  meta: ^1.16.0
  vm_service: ^15.0.0
  path: ^1.9.1
  image: ^4.5.2
  archive: ^4.0.2
  collection: ^1.19.1
  unicode: ^1.1.8
  source_helper: ^1.3.7
  fuzzywuzzy: ^1.2.0
  hooks: ^1.0.0
  code_assets: ^1.0.0
  package_config: ^2.2.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  intl: ^0.20.2
  lints: ^6.0.0
  test: ^1.24.0
  endec:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  endec_json:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  analyzer: ^8.1.1
  ffigen: ^20.0.0
  yaml: ^3.1.3
  kdl: ^2.0.2
  big_decimal: ^0.5.0
